# Generated by Django 4.2.4 on 2023-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_pic/def.png', null=True, upload_to='profile_pic/'),
        ),
    ]
